name: cast
description: Dart package to discover and connect with Chromecast devices
version: 0.2.0
homepage: https://github.com/jonathantribouharet/flutter_cast

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mdns_plugin: ">=1.1.4 <2.0.0"
  protobuf: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  protoc_plugin: ^19.0.1
