name: cast
description: Dart package to discover and connect with Chromecast devices
version: 1.1.1
homepage: https://github.com/jonathantribouharet/flutter_cast

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bonsoir: ^1.0.1+1
  flutter:
    sdk: flutter
  protobuf: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  protoc_plugin: ^20.0.0
